---
- hosts: localhost
  become: true
  gather_facts: true

  tasks:
  
  - name: install JDK 11
    apt:
      name: openjdk-11-jdk
      state: present

  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download & unarchive
    unarchive:
      src: http://apache.cs.utah.edu/tomcat/tomcat-9/v9.0.45/bin/apache-tomcat-9.0.45.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change ownership
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755

  - name: Copy to Tomcat Users Setting 
    copy:
       src: tomcat-users.xml.j2
       dest: /opt/tomcat/conf/tomcat-users.xml
       mode: 0755

  - name: Download war file from source
    get_url:
      url: https://tomcat.apache.org/tomcat-6.0-doc/appdev/sample/sample.war 
      dest: /opt/tomcat/webapps
      mode: 0755 

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: restarted
      enabled: true
      daemon_reload: true

  - name: Nginx setup
    apt:
      name: nginx
      state: present

  - name: Start nginx
    service:
        name: nginx
        state: started
  - name: Copy the nginx config file and restart nginx
    copy:
      src: tomcat.conf.j2
      dest: /etc/nginx/sites-available/tomcat

  - name: Create Symlink
    file:
      src: /etc/nginx/sites-available/tomcat
      dest: /etc/nginx/sites-enabled/default
      state: link

  - name: Restart Nginx
    service:
      name: nginx
      state: restarted
